name: my-python-tests   # نام workflow

on: [push]   # این workflow با هر بار push کد به مخزن اجرا می‌شود

jobs:
  build:
    runs-on: ubuntu-latest   # استفاده از سیستم‌عامل ubuntu برای اجرا
    steps:
    - name: 1. دریافت کدها
      uses: actions/checkout@v4
    - name: 2. راه‌اندازی Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'   # نسخه مورد نظر پایتون
    - name: 3. نصب پیش‌نیازها
      run: pip install -r requirements.txt   # نصب کتابخانه‌های مورد نیاز از فایل requirements.txt
    - name: 4. اجرای تست‌ها
      run: python test.py   # اجرای فایل تست
