name: Run Python Hello World

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python script
        run: python -c "print('Hello, World!'); print('سلام دنیا!')"
